### ISSUE TITLE
📱 Change eslint typescript packages

### ISSUE THREAD

**Issue by ManAnRuck** [demokratie-live/democracy-client#956] opened 2019-12-07 05:10 UTC
change eslint/typescript linting & prettifier packages to use newer typescript version
https://dev.to/thefinnomenon/react-native-linting-testing-15gf

@react-native-community/eslint-config is not really good maintained

**Comment by ManAnRuck** [comment] 2019-12-14 11:27
no pr for this.

just check if ESLint works fine in viscose (no warnings thrown in Output > ESLint)
yarn lint command works without an error

**Comment by ulfgebhardt** [comment] 2019-12-30 11:59
@ManAnRuck Which repository is affected by this? Clinet only?

**Comment by ManAnRuck** [comment] 2019-12-31 02:20
no, just https://github.com/demokratie-live/democracy-app

**Comment by ulfgebhardt** [comment] 2019-12-31 10:13
Then i guess we can close this -> Travis does the check, right?

**Comment by ManAnRuck** [comment] 2019-12-31 10:35
no, currently travis does not check this

**Comment by ulfgebhardt** [comment] 2020-01-20 11:11
![image](https://user-images.githubusercontent.com/1238238/72722085-cdec7d00-3b7d-11ea-96ea-2bbec93496bc.png)

Works fine. One question tho:
The command `eslint 'src/**/*.{ts,tsx,js,jsx}' --fix` is executed apparently - should we run a `--fix` on every occasion? Shouldnt that be the job of the developer?

**Comment by ManAnRuck** [comment] 2020-01-20 12:37
yes I would do it. less work when there is for example just a space missing.
let the machines let do the work if the developer forget something  ;)

**Comment by ulfgebhardt** [comment] 2020-01-20 13:30
The problem is, that travis will always be successful if using `yarn lint` since it will fix all the errors present in the repo on the fly.
I suggest: Remove the `--fix` flag. It would be totaly fine to use a developer shortcut for linting like `yarn devlint` or similar, which uses the fix flag

**Comment by ManAnRuck** [comment] 2020-01-20 13:37
it's not possible to commit something with lint errors. so this would not be the case. 
(if you ignore the commit hook, and travis will make this job, and there is only a auto fixable issue, travis will commit this)

**Closed** 2020-01-20 13:42 UTC
